// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe5jCsFOkVugEUrRg1AY1JqeMUMvMs_Pc',
    appId: '1:278253588255:web:ceaa8b1e68e19680766a2a',
    messagingSenderId: '278253588255',
    projectId: 'proyectomon-db',
    authDomain: 'proyectomon-db.firebaseapp.com',
    storageBucket: 'proyectomon-db.firebasestorage.app',
    measurementId: 'G-4ECSXTGSDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3BHJgIpDBuYljhsNl2HwCydm0CwytMI',
    appId: '1:278253588255:android:0d3768457faa8ad5766a2a',
    messagingSenderId: '278253588255',
    projectId: 'proyectomon-db',
    storageBucket: 'proyectomon-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPXfV0QJna7NVBAVKET4ZhdVte_g8ktZ4',
    appId: '1:278253588255:ios:e99404f5d910249e766a2a',
    messagingSenderId: '278253588255',
    projectId: 'proyectomon-db',
    storageBucket: 'proyectomon-db.firebasestorage.app',
    iosClientId: '278253588255-847d0fe22isgcg0nd445due1creilp6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectomon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe5jCsFOkVugEUrRg1AY1JqeMUMvMs_Pc',
    appId: '1:278253588255:web:d45c1a4c02409fb8766a2a',
    messagingSenderId: '278253588255',
    projectId: 'proyectomon-db',
    authDomain: 'proyectomon-db.firebaseapp.com',
    storageBucket: 'proyectomon-db.firebasestorage.app',
    measurementId: 'G-J1TKT9D8XT',
  );
}
